# encoding: utf-8

RECOMMEND_LINK = "\n== Are you happy with our work? ==\n\nYou can help us by recommending ICanLocalize to others!\nhttp://www.icanlocalize.com/site/about-us/recommend-icanlocalize/".freeze
RECOMMEND_LINK_HTML = '<p>Are you happy with our work?</p><p>You can help us by recommending ICanLocalize to others! <a href="http://www.icanlocalize.com/site/about-us/recommend-icanlocalize">Recommend us »</a></p>'.freeze.html_safe

DAY_IN_SECONDS = 60 * 60 * 24

# Session management (for TA access)
API_VERSION = 1 # version of the API interface
MAX_USER_SESSIONS = 5 # maximal number of sessions per users
SESSION_TIMEOUT = DAY_IN_SECONDS #  3600 # session timeout in seconds
TAS_TIMEOUT = DAY_IN_SECONDS

DEFAULT_CURRENCY_ID = 1

# This is how much top client really pays from the actual price
TOP_CLIENT_DISCOUNT = BigDecimal('0.9')

XMLRPC_USER_AGENT = 'ICanLocalize.com translation updates'.freeze

# fixed cost of instant translation work
INSTANT_TRANSLATION_COST_PER_WORD = BigDecimal('0.11')
MAX_TIME_TO_TRANSLATE_WORD = 25 # time in seconds the translator is allowed per word

# Base price for software translation cost - used in tests
BASE_SW_TRANSLATION_COST_PER_WORD = BigDecimal('0.07')

PER_PAGE = 15 # Paginator constant - number of items per page
PER_PAGE_SUMMARY = 5 # for home page, where multiple lists may be shown

UTF8_ASIAN_WORDS = 3.0

MAX_STR_LENGTH = 255

# project kinds
TA_PROJECT = 0 # From TA
MANUAL_PROJECT = 1 # Any file (doc, image...)
SIS_PROJECT = 2 # sisulizer file project

# Session kinds
EMBEDDED_SESSION = 1
COMPACT_SESSION = 2

# project sources (doesn't change the way a project works, only allows us to create statistics)
SOURCE_WEBSITE = 0 # normal website projects via TA
SOURCE_HM = 1 # H&M projects
SOURCE_SIS = 2 # Sisulizer project

# user privileges
CLIENT_PRIVILEGES = 1
PARTNER_PRIVILEGES = 1
TRANSLATOR_PRIVILEGES = 2
SUPPORTER_PRIVILEGES = 4
ADMIN_PRIVILEGES = 8
USER_PRIVILEGES = { 'Client' => CLIENT_PRIVILEGES,
                    'Alias' => CLIENT_PRIVILEGES,
                    'Translator' => TRANSLATOR_PRIVILEGES,
                    'Partner' => PARTNER_PRIVILEGES,
                    'Supporter' => SUPPORTER_PRIVILEGES | CLIENT_PRIVILEGES | TRANSLATOR_PRIVILEGES,
                    'Admin' => ADMIN_PRIVILEGES | SUPPORTER_PRIVILEGES | CLIENT_PRIVILEGES | TRANSLATOR_PRIVILEGES }.freeze

# error codes
NO_ERROR = 0
NO_EMAIL_SPECIFIED_ERROR = 1
CANNOT_LOG_IN_ERROR = 2
NOT_LOGGED_IN_ERROR = 3
ACCESS_DENIED_ERROR = 4
NOT_FOUND_ERROR = 5
ONLY_CLIENT_CAN_CREATE_PROJECT_ERROR = 10
PROJECT_ALREADY_EXISTS_ERROR = 11
PROJECT_CANNOT_BE_SAVED_ERROR = 12
PROJECT_NOT_FOUND = 13
PROJECT_NOT_SPECIFIED = 14
REVISION_CANNOT_BE_SAVED_ERROR = 20
BAD_LANGUAGE_SPECIFIED_FOR_REVISION_ERROR = 21
REVISION_NAME_BLANK_ERROR = 22
CANNOT_CREATE_NEW_REVISION_IN_PROJECT_ERROR = 23

# User types
# USER_TYPE_CLIENT = 1   # a client
# USER_TYPE_TRANSLATOR = 2 # a translator
# USER_TYPE_STAFF = 2    # website staff
# USER_TYPE_SYSTEM = 3   # auto-generated by the system

# User status
USER_STATUS_NEW = 0 # just signed up
USER_STATUS_REGISTERED = 1 # verified email address
USER_STATUS_QUALIFIED = 2 # passed translator qualifications
USER_STATUS_CLOSED = 3    # used deleted from the system
USER_STATUS_PRIVATE_TRANSLATOR = 4 # private translator
USER_STATUS_ALIAS = 5 # Alias created by a client

# translator levels
NEW_TRANSLATOR = 0      # new in the system. can only do jobs with review
NORMAL_TRANSLATOR = 1   # normal translator. can do jobs without a reviewer
EXPERT_TRANSLATOR = 2   # expert translator. can review other's work

MIN_RATING_FOR_EXPERT_TRANSLATOR = 500 # beyond this rating, the translator would be an expert

MINIMUM_BID_AMOUNT = BigDecimal('0.09') # minimum amount for a bid
MINIMUM_FIXED_PRICE = BigDecimal('0.09') # minimum fixed price for language pair
# Price per word of review jobs. Percentage of the price of the cost per word
# of a translation job. For instance, if a translation for a given language
# pair costs 0.09 and the review price percentage is 0.5 (50%), the review
# price will be 0.045 per word.
REVIEW_PRICE_PERCENTAGE = BigDecimal('0.5')

# Bid status
BID_GIVEN = 1 # translator has given a bid
BID_ACCEPTED = 2    # bid was accepted
BID_COMPLETED = 3   # client accepted work on that bid, and it's now completed
BID_WAITING_FOR_PAYMENT = 4 # client started a payment for this bid, but the payment is not complete
BID_REFUSED = 10 # bid was refused
BID_CANCELED = 11;    # bid has been canceled
BID_TERMINATED = 12;  # work was terminated via mutual arbitation process
BID_DECLARED_DONE = 13 # the translator declares the work as complete

BID_ASSIGNED_STATUS = [BID_WAITING_FOR_PAYMENT, BID_ACCEPTED, BID_COMPLETED, BID_DECLARED_DONE, BID_TERMINATED].freeze
BID_COMPLETE_STATUS = [BID_COMPLETED, BID_TERMINATED].freeze
BID_ACCEPTED_STATUSES = [BID_ACCEPTED, BID_COMPLETED, BID_DECLARED_DONE, BID_TERMINATED].freeze
BID_WON_STATUS = [BID_WAITING_FOR_PAYMENT, BID_ACCEPTED, BID_COMPLETED, BID_DECLARED_DONE].freeze
BID_WAITING_FOR_REVIEW_STATUS = [BID_DECLARED_DONE, BID_COMPLETED, BID_TERMINATED].freeze

# bid_info record
BID_INFO_LANG_ID = 0
BID_INFO_LANG_NAME = 1
BID_INFO_BID_ID = 2
BID_INFO_AMOUNT_VAL = 3
BID_INFO_AMOUNT_ENA = 4
BID_INFO_COMMENT = 5
BID_INFO_ACTIONS_MASK = 6
BID_INFO_CHAT_ID = 7
BID_INFO_CAN_SHOW = 8
BID_INFO_SHOW_TEXT = 9
BID_INFO_COMPLETION_PERCENTAGE = 10
BID_INFO_ACCEPT_TIME = 11
BID_INFO_EXPIRATION_TIME = 12

# status in TA project file for texts
WORDS_STATUS_DONE = 'Complete'.freeze
WORDS_STATUS_NEW = 'New'.freeze
WORDS_STATUS_MODIFIED = 'Modified'.freeze

WORDS_STATUS_DONE_CODE = 0
WORDS_STATUS_NEW_CODE = 1
WORDS_STATUS_MODIFIED_CODE = 2

WORDS_STATUS = { WORDS_STATUS_DONE => WORDS_STATUS_DONE_CODE,
                 WORDS_STATUS_NEW => WORDS_STATUS_NEW_CODE,
                 WORDS_STATUS_MODIFIED => WORDS_STATUS_MODIFIED_CODE }.freeze

WORDS_STATUS_TEXT = { WORDS_STATUS_DONE_CODE => WORDS_STATUS_DONE,
                      WORDS_STATUS_NEW_CODE => WORDS_STATUS_NEW,
                      WORDS_STATUS_MODIFIED_CODE => WORDS_STATUS_MODIFIED }.freeze

# these are mask bits and must be mutually exclusive
BID_ACTION_MAKE_BID = 1
BID_ACTION_EDIT_BID = 2
BID_ACTION_DELETE_BID = 4
BID_ACTION_ACCEPT_BID = 8
BID_ACTION_FINALIZE_WORK = 16
BID_ACTION_REFUSE_BID = 32
BID_ACTION_CANCEL_BID = 64
BID_ACTION_COMPLETE_PAYMENT = 128
BID_ACTION_DECLARE_DONE = 256
BID_ACTION_SELF_COMPLETE = 512
BID_ACTION_EDIT_AGAIN = 1024
BID_ACTION_COMPLETE_REVIEW = 2048
BID_ACTION_ADD_REVIEW = 4096
BID_ACTION_CANCEL_REVIEW = 8192

EVENT_NEW_BID = 1
EVENT_BID_ACCEPTED = 2
EVENT_BID_COMPLETED = 3
EVENT_NEW_MESSAGE = 4
EVENT_BID_WAITING_PAYMENT = 8
EVENT_ARBITRATION_RESPONSE_NEEDED = 5
EVENT_ARBITRATION_RESPONSE_REQUIRED = 14
EVENT_ARBITRATION_OFFER_MADE = 6
EVENT_ARBITRATION_CLOSED = 7
EVENT_BIDDING_ON_REVISION_CLOSED = 10
EVENT_WORK_NEEDS_TO_COMPLETE = 11
EVENT_BID_ABOUT_TO_GO_TO_ARBITRATION = 12
EVENT_BID_WENT_TO_ARBITRATION = 13
EVENT_TICKET_UPDATE = 15
EVENT_TICKET_CLOSED = 16
EVENT_TICKET_FROM_SUPPORTER = 17
EVENT_WORK_DONE = 18
EVENT_INVOICE_DUE = 19
EVENT_NEW_WEBSITE_TRANSLATION_MESSAGE = 30
EVENT_NEW_WEBSITE_TRANSLATION_CONTRACT = 31
EVENT_NEW_RESOURCE_TRANSLATION_MESSAGE = 35
EVENT_NEW_RESOURCE_TRANSLATION_CONTRACT = 36
EVENT_NEW_LANGUAGE_MANAGER_APPLICATION_MESSAGE = 40
EVENT_NEW_LANGUAGE_MANAGER_APPLICATION_CONTRACT = 41
EVENT_NEW_MANAGED_WORK_MESSAGE = 45
EVENT_NEW_ISSUE_MESSAGE = 50
EVENT_UPDATE_VAT_NUMBER = 60

PROTECTED_EVENTS = [EVENT_ARBITRATION_RESPONSE_REQUIRED].freeze

# Arbitration types
MUTUAL_ARBITRATION_CANCEL_BID = 1
SUPPORTER_ARBITRATION_CANCEL_BID = 2
SUPPORTER_ARBITRATION_WORK_MUST_COMPLETE = 3

MUTUAL_TO_SUPPORTER_ARBITRATION_CHANGES = { MUTUAL_ARBITRATION_CANCEL_BID => SUPPORTER_ARBITRATION_CANCEL_BID }.freeze

# Arbitration states
ARBITRATION_CREATED = 1
ARBITRATION_CLOSED = 2

# Arbitration offer states
OFFER_GIVEN = 1
OFFER_ACCEPTED = 2

# External account types
EXTERNAL_ACCOUNT_PAYPAL = 1
EXTERNAL_ACCOUNT_CREDITCARD = 2
EXTERNAL_ACCOUNT_CHECK = 3
EXTERNAL_ACCOUNT_BANK_TRANSFER = 4
EXTERNAL_ACCOUNT_GOOGLE_CHECKOUT = 5
EXTERNAL_ACCOUNT_2CHECKOUT = 6

PAYPAL_VERIFIED_EMAIL_STATUS = 'verified'.freeze

EXTERNAL_ACCOUNTS_THAT_CAN_DEPOSIT = [EXTERNAL_ACCOUNT_PAYPAL, EXTERNAL_ACCOUNT_CREDITCARD].freeze
EXTERNAL_ACCOUNTS_THAT_CAN_WITHDRAW = [EXTERNAL_ACCOUNT_PAYPAL, EXTERNAL_ACCOUNT_CHECK].freeze

# Money transfer status
TRANSFER_PENDING = 0
TRANSFER_COMPLETE = 1
TRANSFER_REQUESTED = 2
TRANSFER_CANCELED = 3

# Transfer types
TRANSFER_DEPOSIT_TO_BID_ESCROW = 1
TRANSFER_PAYMENT_FROM_BID_ESCROW = 2
TRANSFER_REFUND_FROM_BID_ESCROW = 3
TRANSFER_DEPOSIT_FROM_EXTERNAL_ACCOUNT = 4
TRANSFER_PAYMENT_TO_EXTERNAL_ACCOUNT = 5
TRANSFER_REVERSAL_OF_PAYMENT_TO_EXTERNAL_ACCOUNT = 6
TRANSFER_FEE_FROM_TRANSLATOR = 7 # is not used
TRANSFER_PAYMENT_FOR_INSTANT_TRANSLATION = 8
TRANSFER_PAYMENT_FOR_TA_RENTAL = 9
TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION = 10 # only translation
TRANSFER_PAYMENT_FROM_RESOURCE_TRANSLATION = 11 # payment for the translation
TRANSFER_REFUND_FOR_RESOURCE_TRANSLATION = 12 # canceled translation
TRANSFER_PAYMENT_FROM_RESOURCE_REVIEW = 15 # payment for the review
TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION_WITH_REVIEW = 17 # translation with review
TRANSFER_DEPOSIT_TO_RESOURCE_REVIEW = 18 # only review
TRANSFER_DEPOSIT_TO_PROJECT_REVIEW = 20
TRANSFER_DEPOSIT_FOR_SERVICE_WORK = 22 # withdrawal to root account for service work
TRANSFER_GENERAL_REFUND = 23
TRANSFER_PAYMENT_FROM_KEYWORD_LOCALIZATION = 24
TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION_WITH_REVIEW_AND_KEYWORDS = 25
TRANSFER_DEPOSIT_TO_RESOURCE_REVIEW_WITH_KEYWORDS = 26
TRANSFER_DEPOSIT_TO_RESOURCE_KEYWORDS = 27
TRANSFER_REUSE_KEYWORD = 28
TRANSFER_MANUAL_TO_SYSTEM_ACCOUNT = 29
TRANSFER_TAX_RATE = 30
TRANSFER_VOUCHER = 31

TRANSFER_TYPES = [TRANSFER_DEPOSIT_TO_BID_ESCROW, TRANSFER_PAYMENT_FROM_BID_ESCROW, TRANSFER_REFUND_FROM_BID_ESCROW, TRANSFER_DEPOSIT_FROM_EXTERNAL_ACCOUNT, TRANSFER_PAYMENT_TO_EXTERNAL_ACCOUNT, TRANSFER_REVERSAL_OF_PAYMENT_TO_EXTERNAL_ACCOUNT, TRANSFER_FEE_FROM_TRANSLATOR, TRANSFER_PAYMENT_FOR_INSTANT_TRANSLATION, TRANSFER_PAYMENT_FOR_TA_RENTAL, TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION, TRANSFER_PAYMENT_FROM_RESOURCE_TRANSLATION, TRANSFER_REFUND_FOR_RESOURCE_TRANSLATION, TRANSFER_PAYMENT_FROM_RESOURCE_REVIEW, TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION_WITH_REVIEW, TRANSFER_DEPOSIT_TO_RESOURCE_REVIEW, TRANSFER_DEPOSIT_TO_PROJECT_REVIEW, TRANSFER_DEPOSIT_FOR_SERVICE_WORK, TRANSFER_GENERAL_REFUND, TRANSFER_PAYMENT_FROM_KEYWORD_LOCALIZATION, TRANSFER_DEPOSIT_TO_RESOURCE_TRANSLATION_WITH_REVIEW_AND_KEYWORDS, TRANSFER_DEPOSIT_TO_RESOURCE_REVIEW_WITH_KEYWORDS, TRANSFER_DEPOSIT_TO_RESOURCE_KEYWORDS, TRANSFER_TAX_RATE, TRANSFER_VOUCHER].freeze

FEE_RATE = BigDecimal('0.2')
AFFILIATE_COMMISSION_RATE = BigDecimal('0.3') # calculated out of the fee rate

AFFILIATE_CODE_COOKIE = 'ref'.freeze

# PayPal transaction status text and codes
TXN_CREATED = 1
TXN_COMPLETED = 2
TXN_CANCELED_REVERSAL = 3
TXN_DENIED = 4
TXN_EXPIRED = 5
TXN_FAILED = 6
TXN_PENDING = 7
TXN_PROCESSED = 8
TXN_REFUNDED = 9
TXN_REVERSED = 10
TXN_VOIDED = 11
TXN_UNCLAIMED = 12

TXN_COMPLETED_STRING = 'Completed'.freeze

# invoice status
TXN_PAYMENT_STATUS = { 'Canceled_Reversal' => TXN_CANCELED_REVERSAL,
                       TXN_COMPLETED_STRING => TXN_COMPLETED,
                       'Denied' => TXN_DENIED,
                       'Expired' => TXN_EXPIRED,
                       'Failed' => TXN_FAILED,
                       'Pending' => TXN_PENDING,
                       'Processed' => TXN_PROCESSED,
                       'Refunded' => TXN_REFUNDED,
                       'Reversed' => TXN_REVERSED,
                       'Voided' => TXN_VOIDED,
                       'Unclaimed' => TXN_UNCLAIMED,
                       nil => nil }.freeze

LOCALES = { 'English' => 'en_US',
            'German' => 'de_DE',
            'Spanish' => 'es_ES',
            'French' => 'fr_FR',
            'Russian' => 'ru_RU',
            'Portuguese' => 'pt_BR' }.freeze

LOCALES_FOOTER = [%w(English en_US),
                  %w(Deutsch de_DE),
                  %w(Español es_ES),
                  %w(Français fr_FR)].freeze

DEFAULT_LOCALE = 'en_US'.freeze

MARKUP_DESCRIPTION_URL = 'http://daringfireball.net/projects/markdown/syntax'.freeze

NO_TRANSLATORS_CALLS = {
  'project' => ['create'],
  'chats' => %w(accept_bid refuse_bid set_access transfer_bid_payment finalize_bid finalize_bids),
  'revisions' => %w(create edit_description edit_conditions edit_categories edit_languages edit_source_language
                    edit_project_description edit_release_status),
  'bids' => ['update']
}.freeze

FERRET_INDEX_DIR = File.expand_path("index/#{Rails.env}")

TIME_FORMAT_STRING = '%A %b/%d/%Y %H:%M'.freeze
DATE_FORMAT_STRING = '%b/%d/%Y'.freeze

# number of times to retry a database update
MAX_RETRY_ATTEMPTS = 100

# Alert status
REVISION_BIDDING_CLOSED_ALERT = 1
BID_NEEDS_TO_COMPLETE = 1
BID_ABOUT_TO_GO_TO_ARBITRATION = 2
BID_WENT_TO_ARBITRATION = 3

# days to send alerts
DAYS_TO_SEND_WORK_COMPLETION_ALERT = 7
DAYS_TO_PUT_BID_IN_ARBITRATION = 14

# Support ticket status
SUPPORT_TICKET_CREATED = 1
SUPPORT_TICKET_ANSWERED = 2
SUPPORT_TICKET_WAITING_REPLY = 3
SUPPORT_TICKET_SOLVED = 4
SUPPORT_TICKET_CLOSED = 6
SUPPORT_TICKET_INITIATED_BY_SUPPORTER = 5

CMS_SUPPORTER_EMAIL = 'support@icanlocalize.com'.freeze
SYS_ADMIN_EMAIL = 'amir.helzer@onthegosystems.com'.freeze

# for acts_as_attachment photos
PHOTO_PATH = 'public'.freeze

CAPTCHA_RAND = 'eehelzercaptcha'.freeze

# email text settings
EMAIL_OWNER_TXT = '[ICanLocalize] '.freeze
RAW_EMAIL_SENDER = 'notify@icanlocalize.com'.freeze
EMAIL_SENDER = 'ICanLocalize Team <' + RAW_EMAIL_SENDER + '>'
ANALYTICS_EMAIL_SENDER = 'WPML Team <' + RAW_EMAIL_SENDER + '>'
RAW_EMAIL_PASSWORD = 'Ndh#47ymebW'.freeze

# for newsletter
RAW_NEWSLETTER_SENDER = 'notify@icanlocalize.com'.freeze
NEWSLETTER_SENDER = 'ICanLocalize Team<' + RAW_NEWSLETTER_SENDER + '>'

EMAIL_SIGNATURE = "ICanLocalize Team\nBy OnTheGoSystems".freeze
ANALYTICS_EMAIL_SIGNATURE = "WPML Team\nBy OnTheGoSystems".freeze
EMAIL_SIGNATURE_HTML = 'ICanLocalize Team<br>By OnTheGoSystems'.freeze

# Translator qualification level
TRANSLATOR_PASSED_QUALIFICATION = 1

PRACTICE_USER_EMAIL = 'practiceprojects@icanlocalize.com'.freeze

DEMO_CLIENT_FNAME = 'roger'.freeze
DEMO_CLIENT_LNAME = 'moore'.freeze
DEMO_CLIENT_NICKNAME = 'Demo Client'.freeze
DEMO_CLIENT_EMAIL = 'democlient@icanlocalize.com'.freeze
DEMO_CLIENT_PASSWORD = 'sdlkfj0897bx'.freeze

SYSTEM_CLIENT_EMAILS = [PRACTICE_USER_EMAIL, DEMO_CLIENT_EMAIL].freeze

# Todo list
TODO_STATUS_MISSING = 0
TODO_STATUS_PENDING = 1
TODO_STATUS_DONE = 2

TRANSLATOR_LANGUAGE_NEW = 0
TRANSLATOR_LANGUAGE_REQUEST_REVIEW = 1
TRANSLATOR_LANGUAGE_DECLINED = 2
TRANSLATOR_LANGUAGE_APPROVED = 3

# user verification level
VERIFICATION_PENDING = 0
VERIFICATION_DENIED = 1
VERIFICATION_OK = 2

# error report status
ERROR_REPORT_NEW = 0
ERROR_REPORT_IN_WORK = 1
ERROR_REPORT_RESOLVED = 2

# the generic name of Translation Assistant
TA_GENERIC_NAME = 'Translation Assistant'.freeze

# support department for supporter questions
SUPPORTER_QUESTION = 'Question by supporter'.freeze
SUPPORTER_QUESTION_DESCRIPTION = 'Questions or clarifications by a member of the site staff'.freeze

# support department for supporter questions
SETUP_PROJECT_REQUEST = 'Help setup project'.freeze
SETUP_PROJECT_REQUEST_DESCRIPTION = 'Client needs help setting up a project'.freeze

CMS_SUPPORT_DEPARTMENT = 'CMS website support'.freeze
CMS_SUPPORT_DEPARTMENT_DESCRIPTION = 'Client needs help with CMS site'.freeze

DEPARTMENTS_TO_EXCLUDE_FROM_USER_TICKETS = [SUPPORTER_QUESTION, SETUP_PROJECT_REQUEST, CMS_SUPPORT_DEPARTMENT].freeze

# help placement constants
HELP_PLACEMENT_CLIENT = 1
HELP_PLACEMENT_TRANSLATOR = 2
HELP_PLACEMENT_UNQUALIFIED_TRANSLATOR = 4
HELP_PLACEMENT_UNVERIFIED_IDENTITY = 8
HELP_PLACEMENT_CLIENT_WITHOUT_PROJECT = 16

# statistics codes
STATISTICS_DOCUMENTS = 1
STATISTICS_SENTENCES = 2
STATISTICS_WORDS = 3
STATISTICS_SUPPORT_FILES = 4

# statisitcs status
COUNT_ORIG_LANGUAGE = 0 # the original language count
COUNT_WAITING_FOR_TRANSLATOR = 1
COUNT_BEING_TRANSLATED = 2
COUNT_WAITING_FOR_REVIEWER = 3
COUNT_BEING_REVIEWED = 4
COUNT_TRANSLATED = 10 # translation complete

# user email notifications
NEWSLETTER_NOTIFICATION = 1
DAILY_RELEVANT_PROJECTS_NOTIFICATION = 2
DAILY_ALL_PROJECTS_NOTIFICATION = 4
MONTHLY_STATEMENT_NOTIFICATION = 8

# Newsletter flags
NEWSLETTER_RELEASED = 1
NEWSLETTER_SENT = 2
NEWSLETTER_PUBLIC = 4
NEWSLETTER_FOR_TRANSLATORS = 16
NEWSLETTER_FOR_CLIENTS = 32

NEWSLETTER_PENDING_FOR_CLIENTS = NEWSLETTER_RELEASED | NEWSLETTER_FOR_CLIENTS
NEWSLETTER_PENDING_FOR_CLIENTS_MASK = NEWSLETTER_RELEASED | NEWSLETTER_SENT | NEWSLETTER_FOR_CLIENTS

NEWSLETTER_PENDING_FOR_TRANSLATORS = NEWSLETTER_RELEASED | NEWSLETTER_FOR_TRANSLATORS
NEWSLETTER_PENDING_FOR_TRANSLATORS_MASK = NEWSLETTER_RELEASED | NEWSLETTER_SENT | NEWSLETTER_FOR_TRANSLATORS

ALL_PENDING_NEWSLETTERS = NEWSLETTER_RELEASED
ALL_PENDING_NEWSLETTERS_MASK = NEWSLETTER_RELEASED | NEWSLETTER_SENT

NEWSLETTER_FLAG_TEXT = { NEWSLETTER_RELEASED => 'Released',
                         NEWSLETTER_SENT => 'Sent',
                         NEWSLETTER_PUBLIC => 'Public',
                         NEWSLETTER_FOR_TRANSLATORS => 'Send to translators',
                         NEWSLETTER_FOR_CLIENTS => 'Send to clients' }.freeze

# Translation
TRANSLATION_PENDING_CLIENT_REVIEW = 0
TRANSLATION_NOT_NEEDED = 1
TRANSLATION_NEEDED = 2
TRANSLATION_IN_PROGRESS = 3
TRANSLATION_COMPLETE = 4
TRANSLATION_REFUSED = 5
TRANSLATION_NOT_DELIVERED = 6
TRANSLATION_NEEDS_EDIT = 7
INSUFFICIENT_FUNDS = 8

# Message hold results
MESSAGE_HELD_FOR_TRANSLATION = 0
INSUFFICIENT_FUNDS_TO_HOLD_MESSAGE = 1
MESSAGE_ALREADY_ASSIGNED = 2
NO_MESSAGES_TO_TRANSLATE = 3
HOLD_FOR_TRANSLATION_FAILED = 10 # means, the client can retry

# message completion result
TRANSLATION_COMPLETED_OK = 0
TRANSLATION_NOT_YOUR = 1
BLANK_TRANSLATION_ENTERED = 2
TRANSLATION_ALREADY_COMPLETED = 3
TRANSLATION_FAILED_TO_DECODE = 4
TRANSLATION_MISSING_TOKENS = 5
TRANSLATION_REQUIRES_REVIEW = 6
TRANSLATION_ALREADY_COMPLETED_BY_YOU = 7
TRANSLATION_COMPLETION_FAILED = 10

# release from hold results
MESSAGE_RELEASED_FROM_HOLD = 0
TRANSLATION_NOT_IN_PROGRESS = 4

# private translators
PRIVATE_TRANSLATOR_PENDING = 0
PRIVATE_TRANSLATOR_ACCEPTED = 1
PRIVATE_TRANSLATOR_DENIED = 2

# RAILS_DEFAULT_LOGGER ||= Logger.new("#{Rails.root}/log/#{Rails.env}.log")

# User message masks
USER_MESSAGE_COMPLETE_YOUR_ACCOUNT_SETUP = 1
USER_MESSAGE_ACCOUNT_SETUP_COMPLETE = 2

# website types - this determines the processing type - the kind of project and how to process it
WEBSITE_WORDPRESS = 1
WEBSITE_DRUPAL = 2

# this is only for display purposes (which type of CMS generated the project)
CMS_KIND_DRUPAL = 0
CMS_KIND_WORDPRESS = 1

WEBSITE_DESCRIPTION = { WEBSITE_WORDPRESS => 'WordPress',
                        WEBSITE_DRUPAL => 'Drupal',
                        nil => 'Drupal' }.freeze

CMS_DESCRIPTION = { CMS_KIND_WORDPRESS => 'WordPress',
                    CMS_KIND_DRUPAL => 'Drupal',
                    nil => 'Drupal' }.freeze

MIN_CMS_OFFER_RATE = BigDecimal('0.03')
DEFAULT_COST_PER_PROJECT_TYPE = { WEBSITE_WORDPRESS => BigDecimal('0.04'),
                                  WEBSITE_DRUPAL => BigDecimal('0.07') }.freeze

CMS_REQUEST_CREATING = 0
CMS_REQUEST_WAITING_FOR_PROJECT_CREATION = 1
CMS_REQUEST_PROJECT_CREATION_REQUESTED = 2
CMS_REQUEST_CREATING_PROJECT = 3
CMS_REQUEST_RELEASED_TO_TRANSLATORS = 4
CMS_REQUEST_TRANSLATED = 5
CMS_REQUEST_DONE = 6
CMS_REQUEST_FAILED = 7
CMS_REQUEST_MARKED_FOR_CANCEL = 8

CMS_REQUEST_WAITING_FOR_TAS = [CMS_REQUEST_WAITING_FOR_PROJECT_CREATION, CMS_REQUEST_PROJECT_CREATION_REQUESTED, CMS_REQUEST_CREATING_PROJECT].freeze

TRANSLATION_OFFER_OPEN = 0
TRANSLATION_OFFER_CLOSED = 1
TRANSLATION_OFFER_SUSPENDED = 2

TRANSLATION_CONTRACT_NOT_REQUESTED = 0
TRANSLATION_CONTRACT_REQUESTED = 1
TRANSLATION_CONTRACT_ACCEPTED = 2
TRANSLATION_CONTRACT_DECLINED = 3

# -- display filter

DISPLAY_TRANSLATORS_IN_CATEGORY = 0
DISPLAY_ALL_TRANSLATORS = 1
DISPLAY_INVITED_TRANSLATORS = 2
DISPLAY_ACCEPTED_TRANSLATORS = 3
DISPLAY_APPLIED_TRANSLATORS = 4

CMS_TARGET_LANGUAGE_CREATED = 0
CMS_TARGET_LANGUAGE_ASSIGNED = 1
CMS_TARGET_LANGUAGE_TRANSLATED = 2
CMS_TARGET_LANGUAGE_DONE = 3
CMS_TARGET_LANGUAGE_AWAITING_PAYMENT = 9

TAS_COMMAND_NEW_CMS_REQUEST = 1
TAS_COMMAND_RETRY_CMS_REQUEST = 2

TAS_PROCESSING_TIME = 60 * 60

MAX_COMM_ERRORS = 3

# communication errors
COMM_ERROR_CLOSED = 0
COMM_ERROR_ACTIVE = 1

# communication error codes
COMM_ERROR_FAILED_TO_CREATED_PROJECT = 1
COMM_ERROR_FAILED_TO_RETURN_TRANSLATION = 1000
COMM_ERROR_HTML_PARSE_ERROR = 1001

LAST_TAS_COMMAND_CREATE = 1
LAST_TAS_COMMAND_OUTPUT = 2

# translation pickup type
PICKUP_BY_RPC_POST = 0
PICKUP_BY_POLLING = 1

MAX_ALLOWED_CMS_PROJECTS = 5

# CMS projects notification flags
WEBSITE_NOTIFY_DELIVERY = 1
WEBSITE_NOTIFY_UNTRANSLATED = 2

# who interviews translators
CLIENT_INTERVIEWS_TRANSLATORS = 1

# --- text_resources ---

# resource language status
RESOURCE_LANGUAGE_OPEN = 0
RESOURCE_LANGUAGE_CLOSED = 1

# resource_chat status
RESOURCE_CHAT_NOT_APPLIED = 0
RESOURCE_CHAT_APPLIED = 1
RESOURCE_CHAT_ACCEPTED = 2
RESOURCE_CHAT_DECLINED = 3

TRANSLATION_MANAGER_OPEN = 0
TRANSLATION_MANAGER_CLOSED = 1

RESOURCE_FORMAT_TEXT = 0
RESOURCE_FORMAT_XML1 = 1
RESOURCE_FORMAT_XML2 = 2
RESOURCE_FORMAT_YAML = 3
RESOURCE_FORMAT_ANDROID = 4
RESOURCE_FORMAT_XML3 = 5

LINE_BREAK_WINDOWS = 0
LINE_BREAK_UNIX = 1

# string translation status
STRING_TRANSLATION_COMPLETE = 0
STRING_TRANSLATION_NEEDS_UPDATE = 1
STRING_TRANSLATION_BEING_TRANSLATED = 2
STRING_TRANSLATION_MISSING = 3
STRING_TRANSLATION_DUPLICATE = 4

STRING_TRANSLATION_NEEDS_REVIEW = 5 # this status is not actually assigned to translations

REVIEW_NOT_NEEDED = 0 # client didn't pay for a review
REVIEW_PENDING_ALREADY_FUNDED = 1 # translator completed translation, time for review
REVIEW_COMPLETED = 2 # review is completed
REVIEW_AFTER_TRANSLATION = 3 # client paid for review. first, need to translate

ISSUE_UNCLEAR_ORIGINAL = 1
ISSUE_TRANSLATION_SUGGESTION = 2
ISSUE_INCORRECT_TRANSLATION = 3
ISSUE_GENERAL_QUESTION = 4

ISSUE_KINDS = [ISSUE_GENERAL_QUESTION, ISSUE_UNCLEAR_ORIGINAL, ISSUE_TRANSLATION_SUGGESTION, ISSUE_INCORRECT_TRANSLATION].freeze

ISSUE_OPEN = 0
ISSUE_CLOSED = 1

PLURAL_SEPARATOR = '{ICL_PLURAL}'.freeze

# --- accesskey_ok values ---
ACCESSKEY_NOT_VALIDATED = 0
ACCESSKEY_VALIDATED = 1

# --- resource string comment types ---
COMMENT_KIND_IPHONE = 1
COMMENT_KIND_SQUARE_BRACKETS = 2

# --- project kind for CMS websites ---
TEST_CMS_WEBSITE = 0
DEVELOPMENT_CMS_WEBSITE = 1
PRODUCTION_CMS_WEBSITE = 2

# -- notification codes --
NOTIFICATION_NEED_HELP_WITH_HM = 1
NOTIFICATION_NEW_CMS_REQUEST = 2

# -- size ratio between originals and translations --
SIZE_RATIO_LOW = 0.7
SIZE_RATIO_HIGH = 1.3

# --- rating constants --
RATING_ISSUE_WEIGHT = 3000 * 0.07 * 0.08 # each issue is equivilent to losing 3000 words translation
RATING_BOOKMARK_WEIGHT = 7000.0 * 0.07 * 0.08 # each bookmark is equivilent to translation for 7,000 words

SOFTWARE_RE1 = /%[cduxXefgsp@]/
SOFTWARE_RE2 = /%+[0-9]+\$+[cduxXefgsp@]/
SOFTWARE_RE3 = /%+\.+[0-9]+[cduxXegsp@f]/
SOFTWARE_RE4 = /%(#+)\$[cduxXefgsp@]/

SOFTWARE_RE_COMBINED = /%[cduxXefgsp@]|%+\.+[0-9]+[cduxXegsp@f]/

# --- translation status for resource chats ---
RESOURCE_CHAT_NOTHING_TO_TRANSLATE = 1
RESOURCE_CHAT_PENDING_TRANSLATION = 2
RESOURCE_CHAT_TRANSLATION_COMPLETE = 3
RESOURCE_CHAT_TRANSLATOR_NEEDS_TO_REVIEW = 5
RESOURCE_CHAT_TRANSLATION_REVIEWED = 4

# -- managed work --
MANAGED_WORK_CREATED = 0
MANAGED_WORK_REVIEWING = 1
MANAGED_WORK_COMPLETE = 2
MANAGED_WORK_WAITING_FOR_REVIEWER = 3
MANAGED_WORK_WAITING_FOR_PAYMENT = 4

MANAGED_WORK_INACTIVE = 0
MANAGED_WORK_ACTIVE = 1
MANAGED_WORK_PENDING_PAYMENT = 2
MANAGED_WORK_EDIT_BY_REVIEWER = 3

# -- review types
REVIEW_AND_CREATE_ISSUE = 0
REVIEW_AND_EDIT = 1

# -- webta review status
WEBTA_REVIEW_DISABLE = 0
WEBTA_REVIEW_AND_CREATE_ISSUE = 1
WEBTA_REVIEW_AND_EDIT = 2

FEEDBACK_CREATED = 0
FEEDBACK_HANDLED = 1
FEEDBACK_IGNORED = 2

TM_COMPLETE_MATCHES = 0
TM_PENDING_MATCHES = 1
TM_IGNORE_MATCHES = 2

# -- web messages complex flag --
WEB_MESSAGE_COMPLEX_N_FLAGS = 2

# -- purge steps for text resource projects
TEXT_RESOURCE_PURGE_CHOOSE_FILES = 1
TEXT_RESOURCE_PURGE_FILES_CHOSEN = 2

ICL_CREDIT_FOOTER = { 'Arabic' => 'تمت الترجمة بواسطة أي كان لوكاليز ICanLocalize',
                      'Turkish' => 'ICanLocalize tarafından çevrilmiştir',
                      'Portuguese' => 'Traduzido por ICanLocalize',
                      'Portuguese, Portugal' => 'Traduzido por ICanLocalize',
                      'French' => 'Traduction par IcanLocalize',
                      'Thai' => 'แปลโดย ICanLocalize',
                      'Polish' => 'Tłumaczenie: ICanLocalize',
                      'Hebrew' => 'תורגם על-ידי ICanLocalize',
                      'German' => 'Übersetzt von ICanLocalize',
                      'Korean' => 'ICanLocalize에서 번역하였음',
                      'Finnish' => 'Käännnöksen on toimittanut ICanLocalize',
                      'Spanish' => 'Traducido por ICanLocalize',
                      'Swedish' => 'Översatt av ICanLocalize',
                      'Persian' => 'ترجمه شده توسط آیکن لوکالایز',
                      'Norwegian' => 'Oversatt av ICanLocalize',
                      'Japanese' => 'ICanLocalizeにより翻訳されました',
                      'Dutch' => 'Vertaald door ICanLocalize',
                      'Chinese (Traditional)' => 'ICanLocalize 翻譯',
                      'Italian' => 'Tradotto da ICanLocalize',
                      'Chinese (Simplified)' => '由 ICanLocalize 翻译',
                      'Moldavian' => 'Tradus în limba moldovenească de ICanLocalize',
                      'Indonesian' => 'Diterjemahkan oleh ICanLocalize',
                      'Czech' => 'Přeložili v ICanLocalize',
                      'Greek' => 'Μεταφράστηκε από ICanLocalize',
                      'Catalan' => 'Traduït per ICanLocalize',
                      'Russian' => 'Переведено службой ICanLocalize',
                      'Romanian' => 'Tradus de ICanLocalize',
                      'Hungarian' => 'Fordította: ICanLocalize',
                      'Bulgarian' => 'Преведено от ICanLocalize',
                      'Danish' => 'Oversat af ICanLocalize',
                      'Welsh' => 'Cyfieithwyd gan ICanLocalize',
                      'Ukrainian' => 'Перекладено службою ICanLocalize',
                      'Lithuanian' => 'Vertė ICanLocalize' }.freeze

MY_FIELDS = { 'email' => 'E-Mail',
              'fname' => 'First name',
              'lname' => 'Last name',
              'nickname' => 'Nick name' }.freeze

SINGLE_SITE_SUPPORT_SUBSCRIPTION = 1
MULTI_SITE_SUPPORT_SUBSCRIPTION = 2

# subscription cost in USD
SINGLE_SITE_SUPPORT_COST = 50
DEVELOPER_SUPPORT_COST = 200

# renew duration in months
SUPPORT_RENEW_DURATION_MONTHLY = 0
SUPPORT_RENEW_DURATION_YEARLY = 1

# display options
DISPLAY_WEB_SUPPORTS = 1
DISPLAY_AFFILIATE = 2
DISPLAY_SEARCH = 4
DISPLAY_GLOSSARY = 8

# TU status
TU_INCOMPLETE = 0
TU_COMPLETE = 1

HTML_EMAIL_HEADER = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <style type="text/css">
<!--
HTML {
  font-family: verdana,helvetica,lucida,sans-serif;
  font-size: 13px;
  color:#303030;
  max-width: 700px;
}

TD {
  font-size: 13px;
}

h1{
  color:#144081;
  font-size:160%;
  padding: 0.3em 0 0.1em 0;
  margin: 5px 0 5px 0;
  font-family: "Trebuchet MS",Verdana,Arial,Sans-serif;
  font-weight:bold;
  line-height: 150%;
}
h2{
  color:#606090;
  font-size:135%;
  font-weight:bold;
  padding: 0.2em 0 0.1em 0;
  margin: 1.2em 0 0.2em 0;
}
h3{
  color:#144081;
  font-size:120%;
  font-weight:normal;
  padding-top:4px;
  padding-bottom:7px;
  margin: 5px 0 5px 0;
}
h4{
  margin: 7px 0 4px 0;
}

ul, ol {
  list-style-position: outside;
  padding: 0 0 0 2em;
  margin: 0.2em 0 0.6em 0;
}

li {
  margin: 0 0 0.4em 0;
  padding: 0;
}
P {
  padding: 0.1em 0 0.6em 0;
  margin: 0;
}

.stats {
  font-size: 90%;
  padding: 0px;
  margin: 0px;
  border-top: 1px solid #C2DAFF;
  border-left: 1px solid #C2DAFF;
  empty-cells: show;
  border-collapse: collapse;
}

table.stats td, table.stats th {
  border-left: 0px;
  border-top: 0px;
  border-right: 1px solid #C2DAFF;
  border-bottom: 1px solid #C2DAFF;
}

table.stats tr.headerrow th {
  background-color:#EFEFEF;
  color: #606090;
  font-weight:bold;
  text-align: left;
  padding: 4px;

  border-right: 1px solid #C2DAFF;

  text-decoration:none;

}

table.stats tr.bottomrow td {
  background-color:#C2DAFF;
  text-align: left;
  padding: 4px;

  text-decoration:none;
}

table.stats td {
  text-align: left;
  padding: 4px;
  margin: 0px;

  text-decoration:none;
  background-color: #FFFFFF;
}

.important {
  margin: 1em;
  padding: 1em;
  background-color: #FFFBCC;
  border: 1pt solid #E6DB55;
  color: #000000;
}

.rounded_but_bold {
  background-color: #21759B;
  border: 1pt solid #4090FF;
  padding: 0.5em 1em;
  margin-left: 0.2em;
  margin-right: 0.2em;
  text-decoration: none;
  color: #EAF2FA;
  font-weight: bold;
  -moz-border-radius: 7px;
  -webkit-border-radius: 7px;
}

.comment {
  font-size: 85%;
  color: #707070;
}
-->
     </style>

  </head>
  <body>
<span style="color:#144081; font-size:20pt; display:inline-block; line-height:25pt; font-weight:bold; ">ICanLocalize</span>
<hr style="height: 2px; color:#144081;" /><br />'.freeze

HTML_EMAIL_FOOTER = '<br style="clear: both;" /><p>' + EMAIL_SIGNATURE + '</p></body></html>'

# please run rake password:encrypt when this config is set to true.
HASH_PASSWORD = true

# translator validation in sandbox
AUTOMATIC_TRANSLATOR_APPROVAL = false

# disable internalization (locale links on the page footer)
DISABLE_INTERNALIZATION = true

# ##character length###
COMMON_FIELD = 220
COMMON_NOTE = 65000
PASSWORD_FIELD = 12
ID_FIELD = 7
MONEY_FIELD = 12

# Attachment upload max size
ATTACHMENT_MAX_SIZE = 50000
ZIPPED_FILE_MAX_SIZE = 50000
DOWNLOAD_MAX_SIZE = 20000
IMAGE_MAX_SIZE = 2000
WEB_ATTACHMENT_MAX_SIZE = 2000
XLIFF_MAX_SIZE = 40000

# input field width
COMMON_FIELD_SIZE = 25

# password reset secret key
PASSWORD_HASH_SECRET = 'ee5bdbc736d0f89b2b533e29ac91741357d500362107cdf5d769ac79a2cf257e1a3a4be3efce2a7a771ea40b750cb9c39801f47ddeb2b9a45fd12e492a76994e'.freeze

# Tags need to be scrubbed
BLACKLIST_TAGS = %w(script SCRIPT).freeze
BLACKLIST_ATTR = %w(src).freeze

# profiler
PROFILER_ENABLED = Figaro.env.PERFORMANCE_PROFILER == 'true'

COOKIE_STORE_ENABLED = false

# default cache duration
CACHE_DURATION = 240.hours

# configuration on allow search engines to index and follow translator page
INDEX_TRANSLATOR = false

# while this is true, WEBTA is available only for selected beta translators
WEBTA_BETA = true

# coefficients for job complexity calculation.
COMPLEXITY_COEFFICIENTS = [0.65, 0.75, 0.85, 0.95].freeze

# Threshold for "attention required" and "hurry up"
STATUS_THRESHOLD = 0.25

# people to receive emails with app errors
EMAILS_TO_RECEIVE_ERRORS = %w(icl-development@onthegosystems.com).freeze

# disable 2CO
CO_ENABLED = true

# Expiration time for CmsTargetLanguage records that have never been assigned
# a translator
CMS_TARGET_LANGUAGE_EXPIRATION_MONTHS = 6

# Hide auto-assign interface for translators.
ENABLE_TRANSLATOR_SELF_ASSIGN = true

# enable or disable machine translation
ENABLE_MACHINE_TRANSLATION = true
