Figaro.require_keys(%w(
                      secret_token
                      secret_key_base
                      aws_access_key_id
                      aws_secret_access_key
                      aws_region
                      PAYPAL_URLS
                      PAYPAL_SIG
                      PAYPAL_BUSINESS_EMAIL
                      API_USERNAME
                      API_PASSWORD
                      API_SIGNATURE
                      DB_HOST
                      DB_DATABASE
                      DB_USERNAME
                      DB_PASSWORD
                      email_address
                      email_port
                      email_user_name
                      email_password
                      email_domain
                      TP_URL
                      TP_SUID
                      TP_ACCESSKEY
                      TP_API_VERSION
                      PERFORMANCE_PROFILER
                    ))
