class JSONError < StandardError
  attr_accessor :code, :message, :http_status_code
end

JSON_SUCCESS = 0
WEBSITE_NOT_FOUND = 1
INVALID_PARAMS = 5
WEBSITE_NOT_CREATED = 2
LANGUAGE_NOT_FOUND = 3
WEBSITE_TRANSLATION_OFFER_NOT_CREATED = 4
TRANSLATOR_NOT_FOUND = 5
MALFORMED_XLIFF = 6
TP_ERROR = 7
JSON_FORMAT_ERROR = 8
AUTHORIZATION_ERROR = 9
CMS_REQUEST_NOT_FOUND = 10
XLIFF_NOT_TRANSLATED = 11
JSON_GENERAL_ERROR = 100
