production:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid
sandbox:
  host: localhost
  port: 9011
  pid_file: log/ferret_sandbox.pid
development:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid
test:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid
